### ISSUE TITLE
RuntimeError: Invalid index in scatter at /pytorch/aten/src/TH/generic/THTensorEvenMoreMath.cpp:151

### ISSUE THREAD

**Issue by whisperLiang** [yananren2137/huawei-ai-food-challenge#2]
我在第一个阶段训练的时候，模型到了cutmix的地方出现了这个错误，应该怎么解决呢？

**Comment by yananren2137** [comment]
错误定位在cutmix里面的哪一句

**Comment by whisperLiang** [comment]
Traceback (most recent call last):
  File "train.py", line 193, in <module>
    train_acc, train_loss = train(train_loader, model, criterion, optimizer, epoch, scheduler, mixup=using_cutmix)
  File "train.py", line 71, in train
    output, loss = tools.cutmix(input, target, model, criterion)
  File "/content/drive/Shared drives/Team-Coding-Like-Immortal/huawei-ai-food-challenge/utils/tools.py", line 95, in cutmix
    loss = criterion(output, target_a) * lam + criterion(output, target_b) * (1. - lam)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/drive/Shared drives/Team-Coding-Like-Immortal/huawei-ai-food-challenge/utils/loss.py", line 31, in forward
    targets = torch.zeros(log_probs.size()).scatter_(1, targets.unsqueeze(1).data.cpu(), 1)
RuntimeError: Invalid index in scatter at /pytorch/aten/src/TH/generic/THTensorEvenMoreMath.cpp:151

**Comment by whisperLiang** [comment]
这是完整的错误提示.
